package eric.rules
import com.eric.drools_demo.Session
import com.eric.drools_demo.Msg
import com.eric.drools_demo.Message
import com.eric.drools_demo.Car;
import java.util.List;
import function com.eric.drools_demo.Functions.hello
import function com.eric.drools_demo.Functions.avg

rule "rule1"
    when
        Message(message == "msg1")
    then
        System.out.println( "rule1 ran" );
end

rule "rule2"
    when
        $msgs: Message(message == "msg2")
    then
       // System.out.println($msgs);
        System.out.println( "rule2 ran" );
end

rule "rule3"
    when
        $msgs: Message(message == "msg2") or Msg(name=="msg1")
    then
        System.out.println( "rule3 ran" );
end

rule "rule4"
    when
        $msgs: Message(message == "msg2") and Msg(name=="msg1")
    then
        System.out.println( "rule4 ran" );
end


rule "rule5"
    when
    		accumulate(Car($temp : price );
                $sum : sum( $temp )
                )
    then
        System.out.println( "rule5 ran. sum="+$sum );
end

rule "rule6"
    when
    		$numbers : List()
    		accumulate(Double($temp:doubleValue) from $numbers;
                $sum : sum( $temp )
                )
    then
        System.out.println( "rule6 ran. sum="+$sum );
end


rule "rule7"
    when
        //wrong: hello()
        eval(hello())
    then
        System.out.println( "rule4 ran" );
end


rule "rule8"
    when
        Session($temp:avg(valueOf("scores")))
    then
        System.out.println( "rule8 ran. avg="+$temp );
end

